/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package routing;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author GUERRA
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public ArrayList<Cliente> clientes= new ArrayList<>();  
    public ArrayList<Cliente> centros = new ArrayList<>();
    public File archClientes= null;
    public File archCentros=null;
    public int nclientes=0;
    public int nCentros=0;
    
    public Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panel_configuración = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        text_clientes = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        text_centros = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        consumoBase = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        consumoMax = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        capVehicular = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        porcConvergencia = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        porcPreservacion = new javax.swing.JSpinner();
        jButton3 = new javax.swing.JButton();
        maxPoblacion = new javax.swing.JSpinner();
        porcMutacion = new javax.swing.JSpinner();
        maxGeneraciones = new javax.swing.JSpinner();
        panel_genetico = new javax.swing.JPanel();
        panel_memetico = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1200, 1200));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Ruta de archivo clientes:");

        jButton1.setText("Explorar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        text_clientes.setText("C:\\Users\\GUERRA\\Desktop\\Tesis 2\\Data\\p01.txt");

        jLabel5.setText("Ruta de archivo centros:");

        jButton2.setText("Explorar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setText("Consumo de combustible base:");

        consumoBase.setValue(20);

        jLabel7.setText("Consumo de combustible máximo:");

        consumoMax.setValue(35);

        jLabel8.setText("Capacidad vehícular:");

        capVehicular.setValue(80);

        jLabel9.setText("Máxima población:");

        jLabel10.setText("Máximas generaciones:");

        jLabel11.setText("Porcentaje de mutación:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Configuración del algoritmo memético:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Configuración general de los algoritmos:");

        jLabel3.setText("Porcentaje de convergencia:");

        porcConvergencia.setValue(100);

        jLabel12.setText("Porcentaje de preservación:");

        porcPreservacion.setValue(99);

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setText("Ejecutar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        maxPoblacion.setValue(300);

        porcMutacion.setValue(1);

        maxGeneraciones.setValue(30);

        javax.swing.GroupLayout panel_configuraciónLayout = new javax.swing.GroupLayout(panel_configuración);
        panel_configuración.setLayout(panel_configuraciónLayout);
        panel_configuraciónLayout.setHorizontalGroup(
            panel_configuraciónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_configuraciónLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panel_configuraciónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_configuraciónLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panel_configuraciónLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_configuraciónLayout.createSequentialGroup()
                        .addGroup(panel_configuraciónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panel_configuraciónLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(panel_configuraciónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panel_configuraciónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(text_clientes)
                                    .addComponent(text_centros))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panel_configuraciónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(panel_configuraciónLayout.createSequentialGroup()
                                .addGroup(panel_configuraciónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panel_configuraciónLayout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addGroup(panel_configuraciónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_configuraciónLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel3)
                                        .addGap(38, 38, 38)))
                                .addGap(12, 12, 12)
                                .addGroup(panel_configuraciónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panel_configuraciónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(capVehicular, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(consumoMax, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(consumoBase, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(porcConvergencia, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(panel_configuraciónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(34, 34, 34)
                                .addGroup(panel_configuraciónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(maxGeneraciones, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                                    .addComponent(maxPoblacion)
                                    .addComponent(porcMutacion)
                                    .addComponent(porcPreservacion))))
                        .addGap(25, 25, 25))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_configuraciónLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(209, 209, 209))
        );
        panel_configuraciónLayout.setVerticalGroup(
            panel_configuraciónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_configuraciónLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_configuraciónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jButton1)
                    .addComponent(text_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_configuraciónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jButton2)
                    .addComponent(text_centros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(8, 8, 8)
                .addGroup(panel_configuraciónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(maxPoblacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(consumoBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_configuraciónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(maxGeneraciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(consumoMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_configuraciónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(porcMutacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(capVehicular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(panel_configuraciónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(porcConvergencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(porcPreservacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Configuración", panel_configuración);

        javax.swing.GroupLayout panel_geneticoLayout = new javax.swing.GroupLayout(panel_genetico);
        panel_genetico.setLayout(panel_geneticoLayout);
        panel_geneticoLayout.setHorizontalGroup(
            panel_geneticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );
        panel_geneticoLayout.setVerticalGroup(
            panel_geneticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Algoritmo Genético", panel_genetico);

        javax.swing.GroupLayout panel_memeticoLayout = new javax.swing.GroupLayout(panel_memetico);
        panel_memetico.setLayout(panel_memeticoLayout);
        panel_memeticoLayout.setHorizontalGroup(
            panel_memeticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );
        panel_memeticoLayout.setVerticalGroup(
            panel_memeticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Algoritmo Memético", panel_memetico);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        leerArchivo();
        int maxp=(int)maxPoblacion.getValue();
        int maxg=(int)maxGeneraciones.getValue();
        int capV=(int)capVehicular.getValue();
        int consumoB=(int)consumoBase.getValue();
        int consumoM=(int)consumoMax.getValue();
        int probMut=(int)porcMutacion.getValue();

        Genetico genAlgoritmo= new Genetico(clientes,centros,maxp,maxg,probMut
                ,consumoB,consumoM,capV);        
        Cromosoma mejor1=genAlgoritmo.ejecutar();
        
        
        int porcCon=(int)porcConvergencia.getValue();
        int porcPre=(int)porcPreservacion.getValue();
        Memetico memAlgoritmo= new Memetico(clientes,centros,maxp,maxg,probMut
                ,consumoB,consumoM,capV,porcCon,porcPre);
        Cromosoma mejor2=memAlgoritmo.ejecutar();
    }//GEN-LAST:event_jButton3ActionPerformed
    public void leerArchivo(){
        int n=0;
        try (Scanner scanner = new Scanner(new FileReader(text_clientes.getText()))) {
            while (scanner.hasNext()&& n<=(3+2*nCentros)) {
                if (scanner.hasNextInt() ) {
                    if(n==2) nclientes=scanner.nextInt();
                    else if(n==3) nCentros=scanner.nextInt();
                    else scanner.nextInt();
                } else {                   
                    scanner.next();
                }
                n++;
            }
            n=0;
            int coordX=0,coordY=0,demanda=0,codExt=0;
            while(scanner.hasNext()){
                if (scanner.hasNextInt()){
                    if(n==0) codExt=scanner.nextInt();
                    else if(n==1) coordX=scanner.nextInt();
                    else if(n==2) coordY=scanner.nextInt();
                    else if(n==4) {
                        demanda=scanner.nextInt();
                        if(clientes.size()<nclientes)
                            clientes.add(new Cliente(codExt,coordX,coordY,demanda));
                        else centros.add(new Cliente(codExt,coordX,coordY,demanda));
                    }
                    else scanner.nextInt();
                }
                else scanner.next();
                n++;
                if(n==5){
                    n=0;
                    scanner.nextLine();
                }
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser= new JFileChooser();
        chooser.showOpenDialog(null);
        archClientes= chooser.getSelectedFile();
        String fileName=archClientes.getAbsolutePath();
        text_clientes.setText(fileName);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser= new JFileChooser();
        chooser.showOpenDialog(null);
        archCentros= chooser.getSelectedFile();
        String fileName=archCentros.getAbsolutePath();
        text_centros.setText(fileName);        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner capVehicular;
    private javax.swing.JSpinner consumoBase;
    private javax.swing.JSpinner consumoMax;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JSpinner maxGeneraciones;
    private javax.swing.JSpinner maxPoblacion;
    private javax.swing.JPanel panel_configuración;
    private javax.swing.JPanel panel_genetico;
    private javax.swing.JPanel panel_memetico;
    private javax.swing.JSpinner porcConvergencia;
    private javax.swing.JSpinner porcMutacion;
    private javax.swing.JSpinner porcPreservacion;
    private javax.swing.JTextField text_centros;
    private javax.swing.JTextField text_clientes;
    // End of variables declaration//GEN-END:variables
}
